### ISSUE TITLE
Замечания по Лабораторной работе №1 "findtext"

### ISSUE THREAD

**Issue by AniSkyWorker** [Lena2112/OOP#1]
1 Не имеет никакого смысла передача аргументов по константному значению там, где подразумевается, что переданный аргумент не будет изменен, при передаче по значению произойдет копирование исходной переменной, вместо этого используйте константные ссылки

``` C++
bool ValidateTheVariables(ifstream &input, string stringToFind); //необхожима копия, с которой будут производиться вычисления и т.п.  - передаем по значению
bool ValidateTheVariables(ifstream &input, const string & stringToFind); // если подразумеваем константность, передаем по ссылке
```

2 Имена функций должны быть понятными, но краткими, использование артикля the - излишне.
3 Если используется тип bool, то название должно быть говорящим о возвращаемом типе. Кроме того, variables(переменные) - неподходящее название для аргументов, переданных из командной строки. Лучше разделить на две функции или придумать более нейтральное название.

4 Если тип функции - bool, нужно возвращать true/false, 1 или 0 это C-стиль. 
В дальнейшем, если потребуется больше кодов возврата то следует создать enum. (Cо стандарта C++11 - enum class)

``` C++
enum class ErrorType
{
    InvalidArguments,
    FileOpenFail,
    EmptyString
};

ErrorType ValidateInput(...)
{
...
  if(...)
  {
    return ErrorType::InvalidArguments;
  }
...
}
```

5 Согласно стилю кодирования на парах ООП - все конструкции if, else, else if, while и тд выделяются фигурными скобками, не зависимо от числа строк кода внутри конструкции

``` C++
if (!stringIsFound)
{
       cout << "Not found";
}
```

6 не правильно названы переменные и аргументы:

``` C++
string readsAString;
...
bool stringIsFound = false;
...
string stringToFind; //лучше searchString (searchString)
```

вместо слова "string" лучше использовать "line", артикли не нужны, bool переменные должны начинаться со вспомогательного глагола -"isStringFound"

7 лишние пробелы между функциями и скобками с аргументами "printf ()", "setlocale ()"

8 вместо printf используйте std::cout(он позволяет выводить и числа), вместо "/n" можно использовать std::endl;

``` C++
 printf("%d\n",lineNumber); // cout << linenumber << endl;
```

**Comment by AniSkyWorker** [comment]
9 нет тестов (см. пример https://github.com/alexey-malov/oop/tree/master/labs/lab1/CopyFile)
10 необходимо подредактировать .gitignotre файл, чтобы в репозиторий не попадали файлы сборки, например папки Debug(Release) и т.д. http://webnotes.by/docs/raznoe/pravila-sintaksisa-fayla-gitignore
11 лучше проверять std::string на пустоту методом empty()

``` C++
...
if (stringToFind == "") // if(stringToFind.empty())
...
```

**Comment by AniSkyWorker** [comment]
k=0.5

**Comment by alexey-malov** [comment]
Тесты должны запускаться во всех конфигурациях

**Comment by AniSkyWorker** [comment]
- [ ] вы уже выполняли проверку, не следует лишний раз выполнять одно и то же действие

``` C++
bool ValidateInput(int argc)
{
    ...
    if (argc != 3)
    ...
    return (argc == 3);
}
```

либо после невалидных аргументов возвращайте false, а по умолчанию - true, либо делайте проверку, а в main  по результату выводите сообщение(можно и так, и так, но если судить строго сейчас функция валидации аргументов выполняет два действия валидацию и вывод сообщения, что не совсем замечательно):
- [ ]  bool CheckingOfArguments(...) - лишний предлог в названии, можно просто CheckArguments или ArgumentsChecking. и тоже самое, вы выполняете проверку дважды, не бойтесь лишних строчек кода, бойтесь дублирования уже выполненных операций. ifstream тут тоже можно по константной ссылке, так как не меняете и не работаете с его содержимым
- [ ] в post build event оберните переменную $(TargetPath) в кавычки, это позволит избежать проблем, если по пути к ветке debug встретятся имена папок с пробелами, иначе в test.bat передастся путь до первого пробела. Разделенные пробелами строки воспринимаются как отдельные аргументы
- [ ] если был передан неверный файл, то программа должна иметь код возврата отличный от того, что при корректных аргументах, не зря же функция CheckingOfArguments имеет тип bool)
- [ ] дополните тесты, они не проверяют число переданных аргументов

**Comment by AniSkyWorker** [comment]
k = 0.75

**Comment by alexey-malov** [comment]
Проверено на паре Егором Чернухой.
k=1
@AniSkyWorker можешь закрыть
